name: .NET

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: [self-hosted, windows]
        steps:
            - name: Checkout Repository 
              uses: actions/checkout@V2
