name: .NET

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: [self-hosted, Windows]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Restore Dependencies
              run: dotnet restore ${{ github.workspace }} --runtime win-x64 --no-cache
            
            # - name: Publish
            #   run: dotnet publish ${{ github.workspace }} --runtime ${{ vars.runtime }} --self-contained -Property:PublishDir=${{ github.workspace }}/publish --no-restore --configuration Release