name: .NET

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: [windows-latest]
        steps:
            - name: Echo 
              run: echo "Hello, World!"
