name: .NET

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: [self-hosted, Windows]
        steps:
            - name: Checkout Repository 
              uses: actions/checkout@V2
            
            - name: Restore Dependencies
              run: dotnet restore ${{ github.workspace }} --runtime ${{ vars.runtime }} --no-cache
            
            - name: Publish
              run: dotnet publish ${{ github.workspace }} --runtime ${{ vars.runtime }} --self-contained -Property:PublishDir=${{ github.workspace }}/publish --no-restore --configuration Release